-- Ажурирање поднаслова за псалме 42-133
UPDATE psalms SET subtitle = 'Чежња за Богом у изгнанству' WHERE id = 42;
UPDATE psalms SET subtitle = 'Молитва за помоћ у невољи' WHERE id = 43;
UPDATE psalms SET subtitle = 'Молитва за народ у невољи' WHERE id = 44;
UPDATE psalms SET subtitle = 'Бог је наше уточиште' WHERE id = 45;
UPDATE psalms SET subtitle = 'Бог је наша тврђава' WHERE id = 46;
UPDATE psalms SET subtitle = 'Хвала Богу, Цару над земљом' WHERE id = 47;
UPDATE psalms SET subtitle = 'О сујети богатства' WHERE id = 48;
UPDATE psalms SET subtitle = 'Бог суди свету' WHERE id = 49;
UPDATE psalms SET subtitle = 'Покајнички псалам' WHERE id = 50;
UPDATE psalms SET subtitle = 'Молитва за избављење од прогонитеља' WHERE id = 51;
UPDATE psalms SET subtitle = 'О безумљу безбожника' WHERE id = 52;
UPDATE psalms SET subtitle = 'Молитва за помоћ против непријатеља' WHERE id = 53;
UPDATE psalms SET subtitle = 'Молитва у невољи и издаји' WHERE id = 54;
UPDATE psalms SET subtitle = 'Молитва за избављење од страха' WHERE id = 55;
UPDATE psalms SET subtitle = 'Молитва за заштиту' WHERE id = 56;
UPDATE psalms SET subtitle = 'Молитва за правду' WHERE id = 57;
UPDATE psalms SET subtitle = 'Молитва против злих' WHERE id = 58;
UPDATE psalms SET subtitle = 'Молитва за победу у рату' WHERE id = 59;
UPDATE psalms SET subtitle = 'Молитва за помоћ и заштиту' WHERE id = 60;
UPDATE psalms SET subtitle = 'Поверење у Бога' WHERE id = 61;
UPDATE psalms SET subtitle = 'Чежња за Богом' WHERE id = 62;
UPDATE psalms SET subtitle = 'Молитва за избављење од непријатеља' WHERE id = 63;
UPDATE psalms SET subtitle = 'Хвала Богу за жетву и благослове' WHERE id = 64;
UPDATE psalms SET subtitle = 'Хвала Богу за чудеса' WHERE id = 65;
UPDATE psalms SET subtitle = 'Молитва за благослов народа' WHERE id = 66;
UPDATE psalms SET subtitle = 'Бог устаје' WHERE id = 67;
UPDATE psalms SET subtitle = 'Молитва у великој невољи' WHERE id = 68;
UPDATE psalms SET subtitle = 'Молитва за брзу помоћ' WHERE id = 69;
UPDATE psalms SET subtitle = 'Молитва старца' WHERE id = 70;
UPDATE psalms SET subtitle = 'Царски псалам' WHERE id = 71;
UPDATE psalms SET subtitle = 'О праведности Божијој' WHERE id = 72;
UPDATE psalms SET subtitle = 'Тужба због уништења Светиње' WHERE id = 73;
UPDATE psalms SET subtitle = 'Хвала Богу, Судији' WHERE id = 74;
UPDATE psalms SET subtitle = 'Бог је страшан Судија' WHERE id = 75;
UPDATE psalms SET subtitle = 'Молитва у невољи' WHERE id = 76;
UPDATE psalms SET subtitle = 'Божја верност у историји Израиља' WHERE id = 77;
UPDATE psalms SET subtitle = 'Молитва за обнову Сиона' WHERE id = 78;
UPDATE psalms SET subtitle = 'Молитва за обнову Израиља' WHERE id = 79;
UPDATE psalms SET subtitle = 'Позив на покајање' WHERE id = 80;
UPDATE psalms SET subtitle = 'Бог суди боговима' WHERE id = 81;
UPDATE psalms SET subtitle = 'Молитва против непријатеља Израиља' WHERE id = 82;
UPDATE psalms SET subtitle = 'Чежња за домом Божијим' WHERE id = 83;
UPDATE psalms SET subtitle = 'Молитва за благослов и мир' WHERE id = 84;
UPDATE psalms SET subtitle = 'Молитва за милост' WHERE id = 85;
UPDATE psalms SET subtitle = 'Слава Сиона' WHERE id = 86;
UPDATE psalms SET subtitle = 'Молитва у дубокој невољи' WHERE id = 87;
UPDATE psalms SET subtitle = 'Божја верност и Давидов завет' WHERE id = 88;
UPDATE psalms SET subtitle = 'Молитва за мудрост' WHERE id = 89;
UPDATE psalms SET subtitle = 'Под заштитом Свевишњега' WHERE id = 90;
UPDATE psalms SET subtitle = 'Хвала Богу за Његову верност' WHERE id = 91;
UPDATE psalms SET subtitle = 'Господ царује' WHERE id = 92;
UPDATE psalms SET subtitle = 'Бог је Судија' WHERE id = 93;
UPDATE psalms SET subtitle = 'Позив на поклоњење' WHERE id = 94;
UPDATE psalms SET subtitle = 'Певајте Господу песму нову' WHERE id = 95;
UPDATE psalms SET subtitle = 'Господ царује, нека се радује земља' WHERE id = 96;
UPDATE psalms SET subtitle = 'Господ је дошао да суди' WHERE id = 97;
UPDATE psalms SET subtitle = 'Певајте Господу песму нову' WHERE id = 98;
UPDATE psalms SET subtitle = 'Служите Господу с радошћу' WHERE id = 99;
UPDATE psalms SET subtitle = 'Милост и суд' WHERE id = 100;
UPDATE psalms SET subtitle = 'Молитва у невољи' WHERE id = 101;
UPDATE psalms SET subtitle = 'Благосиљај, душо моја, Господа' WHERE id = 102;
UPDATE psalms SET subtitle = 'Благосиљај, душо моја, Господа' WHERE id = 103;
UPDATE psalms SET subtitle = 'Хвала Богу за чудеса у природи' WHERE id = 104;
UPDATE psalms SET subtitle = 'Божја верност и неверност Израиља' WHERE id = 105;
UPDATE psalms SET subtitle = 'Хвала Богу за избављење' WHERE id = 106;
UPDATE psalms SET subtitle = 'Позив на хвалу' WHERE id = 107;
UPDATE psalms SET subtitle = 'Молитва против непријатеља' WHERE id = 108;
UPDATE psalms SET subtitle = 'Псалам о Месији' WHERE id = 109;
UPDATE psalms SET subtitle = 'Хвала Богу за Његову доброту' WHERE id = 110;
UPDATE psalms SET subtitle = 'Хвала Богу за Његову праведност' WHERE id = 111;
UPDATE psalms SET subtitle = 'Хвала Богу, Који подиже сиромашне' WHERE id = 112;
UPDATE psalms SET subtitle = 'Излазак из Египта' WHERE id = 113;
UPDATE psalms SET subtitle = 'Хвала Богу за избављење' WHERE id = 114;
UPDATE psalms SET subtitle = 'Не нама, Господе' WHERE id = 115;
UPDATE psalms SET subtitle = 'Хвалите Господа, сви народи' WHERE id = 116;
UPDATE psalms SET subtitle = 'Хвала Господу, јер је добар' WHERE id = 117;
UPDATE psalms SET subtitle = 'Велики псалам о Закону Божијем' WHERE id = 118;
UPDATE psalms SET subtitle = 'Молитва у невољи' WHERE id = 119;
UPDATE psalms SET subtitle = 'Помоћ долази од Господа' WHERE id = 120;
UPDATE psalms SET subtitle = 'Радост због Јерусалима' WHERE id = 121;
UPDATE psalms SET subtitle = 'Молитва за милост' WHERE id = 122;
UPDATE psalms SET subtitle = 'Избављење од непријатеља' WHERE id = 123;
UPDATE psalms SET subtitle = 'Господ чува народ Свој' WHERE id = 124;
UPDATE psalms SET subtitle = 'Повратак из ропства' WHERE id = 125;
UPDATE psalms SET subtitle = 'Благослов дома' WHERE id = 126;
UPDATE psalms SET subtitle = 'Благослов праведника' WHERE id = 127;
UPDATE psalms SET subtitle = 'Молитва против непријатеља Сиона' WHERE id = 128;
UPDATE psalms SET subtitle = 'Из дубине вапијем' WHERE id = 129;
UPDATE psalms SET subtitle = 'Смирење душе' WHERE id = 130;
UPDATE psalms SET subtitle = 'Господ и Давидов завет' WHERE id = 131;
UPDATE psalms SET subtitle = 'О братској љубави' WHERE id = 132;
UPDATE psalms SET subtitle = 'Благосиљајте Господа' WHERE id = 133;